export const CHANGE_LOADING = 'CHANGE_LOADING';
export type CHANGE_LOADING = typeof CHANGE_LOADING;

export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export type CHANGE_ROUTE = typeof CHANGE_ROUTE;

export const RECEIVE_PRODUCT_LIST = 'RECEIVE_PRODUCT_LIST';
export type RECEIVE_PRODUCT_LIST = typeof RECEIVE_PRODUCT_LIST;

export const RECEIVE_PRODUCT_INFOS = 'RECEIVE_PRODUCT_INFOS';
export type RECEIVE_PRODUCT_INFOS = typeof RECEIVE_PRODUCT_INFOS;