export const CHANGE_LOADING = 'CHANGE_LOADING';
export type CHANGE_LOADING = typeof CHANGE_LOADING;

export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export type CHANGE_ROUTE = typeof CHANGE_ROUTE;

export const RECEIVE_PRODUCT_LIST = 'RECEIVE_PRODUCT_LIST';
export type RECEIVE_PRODUCT_LIST = typeof RECEIVE_PRODUCT_LIST;

export const RECEIVE_PRODUCT_INFOS = 'RECEIVE_PRODUCT_INFOS';
export type RECEIVE_PRODUCT_INFOS = typeof RECEIVE_PRODUCT_INFOS;

export const RECEIVE_CURRENT_PRODUCT = 'RECEIVE_CURRENT_PRODUCT';
export type RECEIVE_CURRENT_PRODUCT = typeof RECEIVE_CURRENT_PRODUCT;

export const UPDATE_CART = 'UPDATE_CART';
export type UPDATE_CART = typeof UPDATE_CART;

export const RECEIVE_POST_LIST = 'RECEIVE_POST_LIST';
export type RECEIVE_POST_LIST = typeof RECEIVE_POST_LIST;

export const RECEIVE_USERINFO = 'RECEIVE_USERINFO';
export type RECEIVE_USERINFO = typeof RECEIVE_USERINFO;

export const RECEIVE_POST_DETAIL = 'RECEIVE_POST_DETAIL';
export type RECEIVE_POST_DETAIL = typeof RECEIVE_POST_DETAIL;

export const RECEIVE_RECOMMEND_POST = 'RECEIVE_RECOMMEND_POST';
export type RECEIVE_RECOMMEND_POST = typeof RECEIVE_RECOMMEND_POST;